### ISSUE TITLE
error in from tf_nms3d import NMS3D ImportError: dynamic module does not define module export function (PyInit_tf_nms3d)

### ISSUE THREAD

**Issue by 619862306** [qq456cvb/VoteNet#14]
when i run the run.py:
`Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from model import Model
  File "/home/zdi/VoteNet/model.py", line 15, in <module>
    from tf_nms3d import NMS3D
ImportError: dynamic module does not define module export function (PyInit_tf_nms3d)`

and my tf_mns3d_compile.sh is :
`g++ -std=c++11 tf_nms3d.cpp -o tf_nms3d_so.so -shared -fPIC -I /home/zdi/.conda/envs/py36_tf/lib/python3.6/site-packages/tensorflow/include -I /usr/local/cuda-9.0/include -I /home/zdi/.conda/envs/py36_tf/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-9.0/lib64/ -L/home/zdi/.conda/envs/py36_tf/lib/python3.6/site-packages/tensorflow -ltensorflow_framework -O2 `

however, when i run 'tf_nms3d.py', the terminal print out an array with no errors:
`[0 1]
 [0 0]]
Process finished with exit code 0`

my environment is ubuntu 16 + cuda 9 + tf 1.12.0

who can help me handle this problem, thanks very much !

**Comment by 619862306** [comment]
当我切换至python2.7时，上述错误可以被解决，但是会报其他错误，类似于：

`AttributeError:'module' object has no attribute 'lru_cache'.`

这是因为作者您使用的代码应该是python3.4+，python2.7不支持这些包。

在我使用上述的tf_mns3d_compile.sh文件编译时，tf_nms3d.py是可以运行的，

但是在主文件run.py运行时，会报错：
`from tf_nms3d import NMS3D
ImportError: dynamic module does not define module export function (PyInit_tf_nms3d)`
